from enum import Enum


class EventTypes(Enum):
    BID_APPLIED = "bid_applied"
    DONATION_RECEIVED = "donation_received"
    HOST_SHIFT_ENDED = "host_shift_ended"
    HOST_SHIFT_STARTED = "host_shift_started"
    INCENTIVE_MET = "incentive_met"
    INCENTIVE_OPENED = "incentive_opened"
    METRIC_EVENT_DONATION_TOTAL = "metric_event_donation_total"
    METRIC_TWITCH_CHANNEL_VIEWERSHIP = "metric_twitch_channel_viewership"
    PRIZE_CLOSED = "prize_closed"
    PRIZE_OPENED = "prize_opened"
    RUN_COMPLETED = "run_completed"
    RUN_STARTED = "run_started"
    TWITCH_CHANNEL_HYPE_TRAIN_ENDED = "twitch_channel_hype_train_ended"
    TWITCH_CHANNEL_HYPE_TRAIN_STARTED = "twitch_channel_hype_train_started"
    TWITCH_CHANNEL_HYPE_TRAIN_UPDATED = "twitch_channel_hype_train_updated"
    TWITCH_CHANNEL_POLL_ENDED = "twitch_channel_poll_ended"
    TWITCH_CHANNEL_POLL_STARTED = "twitch_channel_poll_started"
    TWITCH_CHANNEL_POLL_UPDATED = "twitch_channel_poll_updated"
    TWITCH_CHANNEL_PREDICTION_ENDED = "twitch_channel_prediction_ended"
    TWITCH_CHANNEL_PREDICTION_LOCKED = "twitch_channel_prediction_locked"
    TWITCH_CHANNEL_PREDICTION_STARTED = "twitch_channel_prediction_started"
    TWITCH_CHANNEL_PREDICTION_UPDATED = "twitch_channel_prediction_updated"
    TWITCH_CHANNEL_RAID_RECEIVED = "twitch_channel_raid_received"
    TWITCH_CHANNEL_UPDATED = "twitch_channel_updated"
    TWITCH_STREAM_ENDED = "twitch_stream_ended"
    TWITCH_STREAM_STARTED = "twitch_stream_started"
    TWITCH_USER_CHEERED = "twitch_user_cheered"
    TWITCH_USER_FOLLOWED = "twitch_user_followed"
    TWITCH_USER_POINTS_REWARD_REDEEMED = "twitch_user_points_reward_redeemed"
    TWITCH_USER_SUBSCRIBED = "twitch_user_subscribed"
    TWITCH_USER_SUBSCRIPTION_EXPIRED = "twitch_user_subscription_expired"
    TWITCH_USER_SUBSCRIPTION_GIFTED = "twitch_user_subscription_gifted"
